language: python
dist: xenial
sudo: true
services:
- docker
matrix:
  include:
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=py36-functional
  - python: 3.6
    env: TOXENV=coverage,codecov
  - python: 3.7
    env: TOXENV=py37
  - python: 3.7
    env: TOXENV=py37-functional
install:
- pip install tox
script:
- tox
notifications:
  email: false
  slack:
    secure: U8IAfAMRqrFPOZ1alfGCgAfTEIclxO0WFbyOXHkZyJk/ZujW2FAZkyshWOxCcAYlVMaAfO8dG5XT/OaQ2LVUmYXPCf73bVNARxz448k0JpAeLtyaWSmGSG2o9hJt5tOXohTqg5hDHX6BI1xJNLbRkVdLpOpmrH6xNl99OxAEqBQDJHo9OdESeN+5x441sjuCJlYcaN5kx6tjRWAaEIwakZNcLNauktwdvJJgq3FYSeB/VnHELGxpXMV2MA+558QTANcELUD6azD5wDVMRa+bonDsNVoBImAL2N/2xwtvSccsvnTl9mhCgoX+gM0SVODXam+cCVOmwBJzdt7fhtPZ2K7PvMNhwc+n6NxZkWagax+HcYbrz0NMj+i3JunEj2QzOILJOrgf9ARtnFgxsdLAsX/8HVrJjdRKRJkwa0TkdSgPEcZWpYxW84TVOL2OfzB72vsnnl3sRDQYgcxTy/u2qb1Pqx+1lIG7vSRusFn+3usz0TEcpX45MHxInyTKfd6Bm6Eu4pZO4vYXWP4bMRFnDNagK6FmKvXtlz2BV951cTTlThCopMmQJYPIShcV0Lc1fpDg/x674OXSRxL+p97Tzz3doD+uxXVACxHzsnpiUq98X0txUJpL3jgXoDRVVmybIvaNguwY1Wm03IR0zUd6v1pWMuRpx1V9RG6wpekqGOI=
