version: '3.3'

services:
  dashboard-frontend:
    container_name: dashboard-frontend
    build:
      context: ..
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ../:/root/dashboard
    environment:
      NODE_ENV: production
      API_HOST: ${API_HOST:-http://localhost}
      API_PORT: 18080
      DRUCKER_DASHBOARD_FRONTEND_PORT: ${DRUCKER_DASHBOARD_FRONTEND_PORT:-8080}
    command:
      - /bin/bash
      - -c
      - "cd frontend && yarn install && yarn run build && yarn run start:prod"
    depends_on:
      - dashboard-backend
    ports:
      - "${DRUCKER_DASHBOARD_FRONTEND_PORT:-8080}:${DRUCKER_DASHBOARD_FRONTEND_PORT:-8080}"
    restart: always
  dashboard-backend:
    container_name: dashboard-backend
    build:
      context: ..
      dockerfile: ./drucker_dashboard/Dockerfile
    volumes:
      - ../:/root/dashboard
    environment:
      FLASK_DEBUG: "False"
      PYTHONIOENCODING: "utf-8"
    command:
      - /bin/bash
      - -c
      - "pip install -r requirements.txt && pip install -e . && cd drucker_dashboard && (rekcurdui --settings settings.yml db init || true) && (rekcurdui --settings settings.yml db migrate || true) && rekcurdui --settings settings.yml server"
    ports:
      - "18080:18080"
    restart: always
