version: '3.3'

services:
  dashboard-frontend-dev:
    container_name: drucker-dashboard-frontend-dev-for-aws
    build:
      context: ../..
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ../../frontend:/root/drucker-dashboard
    environment:
      API_HOST: ${API_HOST:-http://localhost}
      API_PORT: 18080
    command:
      - /bin/bash
      - -c
      - "yarn install && yarn run start"
    depends_on:
      - dashboard-backend-dev
    ports:
      - "8080:8080"
  dashboard-backend-dev:
    container_name: drucker-dashboard-backend-dev-for-aws
    build:
      context: ../..
      dockerfile: ./app/Dockerfile_aws
    volumes:
      - ../../app:/root/drucker-dashboard
      - ~/.aws:/root/.aws
    environment:
      FLASK_DEBUG: "True"
      PYTHONIOENCODING: "utf-8"
    command:
      - /bin/bash
      - -c
      - "sh start.sh"
    ports:
      - "18080:18080"
