version: '3.3'

services:
  dashboard-frontend:
    container_name: dashboard-frontend-for-aws
    build:
      context: ../..
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ../../:/root/dashboard
    environment:
      NODE_ENV: production
      API_HOST: ${API_HOST:-http://localhost}
      API_PORT: 18080
      REKCURD_DASHBOARD_FRONTEND_PORT: ${REKCURD_DASHBOARD_FRONTEND_PORT:-8080}
    command:
      - /bin/bash
      - -c
      - "cd frontend && yarn install && yarn run build && yarn run start:prod"
    depends_on:
      - dashboard-backend
    ports:
      - "${REKCURD_DASHBOARD_FRONTEND_PORT:-8080}:${REKCURD_DASHBOARD_FRONTEND_PORT:-8080}"
    restart: always
  dashboard-backend:
    container_name: dashboard-backend-for-aws
    build:
      context: ../..
      dockerfile: ./rekcurd_dashboard/Dockerfile
    volumes:
      - ../../:/root/dashboard
      - ~/.aws:/root/.aws
    environment:
      FLASK_DEBUG: "False"
      PYTHONIOENCODING: "utf-8"
    command:
      - /bin/bash
      - -c
      - "pip install -r requirements.txt && pip install -e . && cd rekcurd_dashboard && (rekcurdui --settings settings.yml db init || true) && (rekcurdui --settings settings.yml db migrate || true) && rekcurdui --settings settings.yml server"
    ports:
      - "18080:18080"
    restart: always
