apiVersion: v1
kind: Service
metadata:
  labels:
    app: rekcurd-test-app
    sel: rekcurd-test-app-development-20180628151929
  name: rekcurd-test-app-development-20180628151929-service
  namespace: development
spec:
  ports:
  - name: http2
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    sel: rekcurd-test-app-development-20180628151929
  type: NodePort
