apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: rekcurd-test-app
    sel: rekcurd-test-app-development-20180628151929
  name: rekcurd-test-app-development-20180628151929-autoscaling
  namespace: development
spec:
  maxReplicas: 10
  metrics:
  - resource:
      name: cpu
      targetAverageUtilization: 80
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1beta2
    kind: Deployment
    name: rekcurd-test-app-development-20180628151929-deployment
